name: Build Artifacts

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        source_branch: [sdk2013-mp]

    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - name: Install Dependencies
      run: |
        dpkg --add-architecture i386
        apt update
        apt install -y build-essential git libstdc++6:i386 gcc-multilib g++-multilib

    - name: Checkout Mini Source SDK
      uses: actions/checkout@v3
      with:
        repository: Joshua-Ashton/mini-source-sdk

    - name: Checkout VPhysics Jolt
      uses: actions/checkout@v3
      with:
        path: ${{ matrix.source_branch }}/src/vphysics_jolt
        submodules: recursive

    - name: Build GCC x86
      working-directory: ${{ matrix.source_branch }}/src
      run: |
        ./createjoltprojects.sh
        make -f jolt.mak -j $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vphysics_jolt_${{ matrix.source_branch }}_linux32
        path: ${{ matrix.source_branch }}/game
        if-no-files-found: error
